@startuml
/'
Module:	employee_details.plantuml
Function:
        PlantUML source for employee details.
	
Copyright:
        This file copyright (C) 2022 by

        MCCI Corporation
        3520 Krums Corners Road
        Ithaca, NY 14850

        An unpublished work. All rights reserved.

        This file is proprietary information, and may not be disclosed or
        copied without the prior permission of MCCI Corporation.

	
Author:
        Pranau R, MCCI Corporation	April 2022

'/

start

:Create a base class with members to 
          get basic employee detail;
:Get the details from user and store them in respective
            data members using member functions;
:Now inherit base class into a new sub-class;
:Display menu;
:Read choice;

while (choice is not exit) is (yes)

fork

-> case1;
:Get Employee details;

fork again

-> case2;
:Display details;

fork again
->case3;
:Modify input;

end fork

:Read choice;

end while

stop

@enduml